apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p9jbakpud-python
  janus-idp.io/tekton: p9jbakpud-python
  backstage.io/kubernetes-id: p9jbakpud-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p9jbakpud-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
